import { letterSchema, parseAll, type Letter } from "@/content/schema";

/**
 * The Gurmukhi letters, in the traditional order learners are taught.
 *
 * Letter names and sound values follow the standard references listed in
 * content/SOURCES.md. Two points most beginner resources get wrong are
 * handled explicitly here:
 *
 *  - ਘ ਝ ਢ ਧ ਭ are not really voiced aspirates in modern Punjabi. They carry a
 *    low tone on the following vowel, which is why ਘਰ sounds closer to "kàr"
 *    than to an English "gh". Learners are told this plainly in `note`.
 *  - ਙ ਞ ਣ ੜ never begin a word, so they are taught for recognition and never
 *    drilled as word-initial sounds.
 *
 * Stroke order is written in plain language. Almost every Gurmukhi letter is
 * built the same way: the body first, then the top bar (ਸਿਰ ਰੇਖਾ) that joins
 * letters into a word, left to right throughout.
 */

const TOP_BAR = "Draw the body of the letter first, then the top bar left to right.";

const raw: unknown[] = [
  /* --------------------------- vowel carriers --------------------------- */
  {
    letter: "ੳ",
    name: "ūṛā",
    nameGurmukhi: "ਊੜਾ",
    sound: "carries the u, ū and o vowels",
    ipa: "—",
    group: "carriers",
    order: 1,
    example: { gurmukhi: "ਉੱਲੂ", roman: "ullū", english: "owl" },
    strokeGuide:
      "Start at the top left, curve down and round to the right like a hook, then add the short top bar.",
    note: "Not a sound of its own. It is a stand for a vowel at the start of a word: ਉ, ਊ, ਓ.",
  },
  {
    letter: "ਅ",
    name: "aiṛā",
    nameGurmukhi: "ਐੜਾ",
    sound: "carries the a, ā, e and ai vowels",
    ipa: "ə",
    group: "carriers",
    order: 2,
    example: { gurmukhi: "ਅੱਜ", roman: "ajj", english: "today" },
    strokeGuide:
      "Draw the left curve downward, then the short stroke on the right, and finish with the top bar.",
    note: "On its own it is a short a. It also carries ਆ, ਏ and ਐ at the start of a word.",
  },
  {
    letter: "ੲ",
    name: "īṛī",
    nameGurmukhi: "ਈੜੀ",
    sound: "carries the i and ī vowels",
    ipa: "—",
    group: "carriers",
    order: 3,
    example: { gurmukhi: "ਇੱਕ", roman: "ikk", english: "one" },
    strokeGuide: "Draw the left stem down, the right stem down, then join them with the top bar.",
    note: "Never used alone. It carries ਇ and ਈ at the start of a word.",
  },

  /* ----------------------------- fricatives ----------------------------- */
  {
    letter: "ਸ",
    name: "sassā",
    nameGurmukhi: "ਸੱਸਾ",
    sound: "s as in sun",
    ipa: "s",
    group: "fricatives",
    order: 4,
    example: { gurmukhi: "ਸੇਬ", roman: "seb", english: "apple" },
    strokeGuide: "Draw the loop on the left, then the stem down on the right, then the top bar.",
  },
  {
    letter: "ਹ",
    name: "hāhā",
    nameGurmukhi: "ਹਾਹਾ",
    sound: "h as in hat",
    ipa: "ɦ",
    group: "fricatives",
    order: 5,
    example: { gurmukhi: "ਹੱਥ", roman: "hatth", english: "hand" },
    strokeGuide: "Draw the small loop, then the vertical stroke down, then the top bar.",
  },

  /* ------------------------------- velars ------------------------------- */
  {
    letter: "ਕ",
    name: "kakkā",
    nameGurmukhi: "ਕੱਕਾ",
    sound: "k as in skin, with no puff of air",
    ipa: "k",
    group: "velars",
    order: 6,
    example: { gurmukhi: "ਕਮਰਾ", roman: "kamrā", english: "room" },
    strokeGuide: "Draw the hook on the left, then the stem down on the right, then the top bar.",
  },
  {
    letter: "ਖ",
    name: "khakkhā",
    nameGurmukhi: "ਖੱਖਾ",
    sound: "kh — like k in kite, with a strong puff of air",
    ipa: "kʰ",
    group: "velars",
    order: 7,
    example: { gurmukhi: "ਖੰਡ", roman: "khaṇḍ", english: "sugar" },
    strokeGuide: TOP_BAR,
    note: "The puff of air is what separates ਖ from ਕ. Hold a hand in front of your mouth to feel it.",
  },
  {
    letter: "ਗ",
    name: "gaggā",
    nameGurmukhi: "ਗੱਗਾ",
    sound: "g as in go",
    ipa: "ɡ",
    group: "velars",
    order: 8,
    example: { gurmukhi: "ਗਾਂ", roman: "gā̃", english: "cow" },
    strokeGuide: TOP_BAR,
  },
  {
    letter: "ਘ",
    name: "ghaggā",
    nameGurmukhi: "ਘੱਗਾ",
    sound: "gh — in practice a k sound with the voice dipping low",
    ipa: "kə̀",
    group: "velars",
    order: 9,
    example: { gurmukhi: "ਘਰ", roman: "ghar", english: "house, home" },
    strokeGuide: TOP_BAR,
    note: "Written gh, but modern Punjabi gives it a low tone: ਘਰ sounds closer to kàr than to an English gh.",
  },
  {
    letter: "ਙ",
    name: "ṅaṅṅā",
    nameGurmukhi: "ਙੰਙਾ",
    sound: "ng as in sing",
    ipa: "ŋ",
    group: "velars",
    order: 10,
    example: { gurmukhi: "ਸਿੰਘ", roman: "siṅgh", english: "lion (as in the name Singh)" },
    strokeGuide: TOP_BAR,
    rare: true,
    neverInitial: true,
    exampleShowsSoundOnly: true,
    note: "Rarely written today. The ng sound is normally written with ਟਿੱਪੀ instead, as in ਸਿੰਘ. Learn to recognise it, no more.",
  },

  /* ------------------------------ palatals ------------------------------ */
  {
    letter: "ਚ",
    name: "caccā",
    nameGurmukhi: "ਚੱਚਾ",
    sound: "ch as in cheese, but lighter and with no puff of air",
    ipa: "t͡ʃ",
    group: "palatals",
    order: 11,
    example: { gurmukhi: "ਚਾਹ", roman: "cāh", english: "tea" },
    strokeGuide: TOP_BAR,
    note: "Written c in this course. English ch is usually closer to ਛ.",
  },
  {
    letter: "ਛ",
    name: "chacchā",
    nameGurmukhi: "ਛੱਛਾ",
    sound: "chh — like ch in cheese with a strong puff of air",
    ipa: "t͡ʃʰ",
    group: "palatals",
    order: 12,
    example: { gurmukhi: "ਛੱਤ", roman: "chatt", english: "roof" },
    strokeGuide: TOP_BAR,
  },
  {
    letter: "ਜ",
    name: "jajjā",
    nameGurmukhi: "ਜੱਜਾ",
    sound: "j as in jam",
    ipa: "d͡ʒ",
    group: "palatals",
    order: 13,
    example: { gurmukhi: "ਜੁੱਤੀ", roman: "juttī", english: "shoe" },
    strokeGuide: TOP_BAR,
  },
  {
    letter: "ਝ",
    name: "jhajjā",
    nameGurmukhi: "ਝੱਜਾ",
    sound: "jh — in practice a ch sound with the voice dipping low",
    ipa: "t͡ʃə̀",
    group: "palatals",
    order: 14,
    example: { gurmukhi: "ਝੰਡਾ", roman: "jhaṇḍā", english: "flag" },
    strokeGuide: TOP_BAR,
    note: "Like ਘ, this one carries a low tone rather than a true jh sound.",
  },
  {
    letter: "ਞ",
    name: "ñaññā",
    nameGurmukhi: "ਞੰਞਾ",
    sound: "ny as in canyon",
    ipa: "ɲ",
    group: "palatals",
    order: 15,
    example: { gurmukhi: "ਪੰਜਾਬੀ", roman: "pañjābī", english: "Punjabi" },
    strokeGuide: TOP_BAR,
    rare: true,
    neverInitial: true,
    exampleShowsSoundOnly: true,
    note: "Almost never written. The sound itself is common — it is the ñ in ਪੰਜਾਬੀ — but ਟਿੱਪੀ is used to write it.",
  },

  /* ---------------------------- retroflexes ----------------------------- */
  {
    letter: "ਟ",
    name: "ṭaiṅkā",
    nameGurmukhi: "ਟੈਂਕਾ",
    sound: "t with the tongue curled back against the roof of the mouth",
    ipa: "ʈ",
    group: "retroflexes",
    order: 16,
    example: { gurmukhi: "ਟਮਾਟਰ", roman: "ṭamāṭar", english: "tomato" },
    strokeGuide: TOP_BAR,
    note: "Closer to the t in English top than ਤ is.",
  },
  {
    letter: "ਠ",
    name: "ṭhaṭṭhā",
    nameGurmukhi: "ਠੱਠਾ",
    sound: "ṭh — curled-back t with a strong puff of air",
    ipa: "ʈʰ",
    group: "retroflexes",
    order: 17,
    example: { gurmukhi: "ਠੀਕ", roman: "ṭhīk", english: "fine, okay" },
    strokeGuide: "Draw the circle, then the line through it, then the top bar.",
  },
  {
    letter: "ਡ",
    name: "ḍaḍḍā",
    nameGurmukhi: "ਡੱਡਾ",
    sound: "d with the tongue curled back",
    ipa: "ɖ",
    group: "retroflexes",
    order: 18,
    example: { gurmukhi: "ਡੱਬਾ", roman: "ḍabbā", english: "box" },
    strokeGuide: TOP_BAR,
  },
  {
    letter: "ਢ",
    name: "ḍhaḍḍā",
    nameGurmukhi: "ਢੱਡਾ",
    sound: "ḍh — in practice a curled-back ṭ with the voice dipping low",
    ipa: "ʈə̀",
    group: "retroflexes",
    order: 19,
    example: { gurmukhi: "ਢੋਲ", roman: "ḍhol", english: "drum" },
    strokeGuide: TOP_BAR,
    note: "Another tonal letter, like ਘ and ਝ.",
  },
  {
    letter: "ਣ",
    name: "ṇāṇā",
    nameGurmukhi: "ਣਾਣਾ",
    sound: "n with the tongue curled back",
    ipa: "ɳ",
    group: "retroflexes",
    order: 20,
    example: { gurmukhi: "ਪਾਣੀ", roman: "pāṇī", english: "water" },
    strokeGuide: TOP_BAR,
    neverInitial: true,
    note: "Never starts a word, but very common inside one. ਪਾਣੀ is the word to remember it by.",
  },

  /* ------------------------------- dentals ------------------------------ */
  {
    letter: "ਤ",
    name: "tattā",
    nameGurmukhi: "ਤੱਤਾ",
    sound: "t with the tongue against the back of the top teeth",
    ipa: "t̪",
    group: "dentals",
    order: 21,
    example: { gurmukhi: "ਤਾਰਾ", roman: "tārā", english: "star" },
    strokeGuide: TOP_BAR,
    note: "Softer than an English t. The tongue touches the teeth, not the ridge behind them.",
  },
  {
    letter: "ਥ",
    name: "thatthā",
    nameGurmukhi: "ਥੱਥਾ",
    sound: "th — dental t with a strong puff of air",
    ipa: "t̪ʰ",
    group: "dentals",
    order: 22,
    example: { gurmukhi: "ਥਾਲੀ", roman: "thālī", english: "plate" },
    strokeGuide: TOP_BAR,
    note: "Not the th of think. It is a t with air behind it.",
  },
  {
    letter: "ਦ",
    name: "daddā",
    nameGurmukhi: "ਦੱਦਾ",
    sound: "d with the tongue against the back of the top teeth",
    ipa: "d̪",
    group: "dentals",
    order: 23,
    example: { gurmukhi: "ਦੁੱਧ", roman: "duddh", english: "milk" },
    strokeGuide: TOP_BAR,
  },
  {
    letter: "ਧ",
    name: "dhaddā",
    nameGurmukhi: "ਧੱਦਾ",
    sound: "dh — in practice a dental t with the voice dipping low",
    ipa: "t̪ə̀",
    group: "dentals",
    order: 24,
    example: { gurmukhi: "ਧੰਨਵਾਦ", roman: "dhannvād", english: "thank you" },
    strokeGuide: TOP_BAR,
    note: "Tonal, like ਘ ਝ ਢ.",
  },
  {
    letter: "ਨ",
    name: "nannā",
    nameGurmukhi: "ਨੰਨਾ",
    sound: "n as in net",
    ipa: "n",
    group: "dentals",
    order: 25,
    example: { gurmukhi: "ਨਾਮ", roman: "nām", english: "name" },
    strokeGuide: TOP_BAR,
  },

  /* ------------------------------- labials ------------------------------ */
  {
    letter: "ਪ",
    name: "pappā",
    nameGurmukhi: "ਪੱਪਾ",
    sound: "p as in spin, with no puff of air",
    ipa: "p",
    group: "labials",
    order: 26,
    example: { gurmukhi: "ਪਿੰਡ", roman: "piṇḍ", english: "village" },
    strokeGuide: TOP_BAR,
  },
  {
    letter: "ਫ",
    name: "phapphā",
    nameGurmukhi: "ਫੱਫਾ",
    sound: "ph — like p in pin, with a strong puff of air",
    ipa: "pʰ",
    group: "labials",
    order: 27,
    example: { gurmukhi: "ਫਲ", roman: "phal", english: "fruit" },
    strokeGuide: TOP_BAR,
    note: "Not an f. The f sound is written ਫ਼, with a dot underneath.",
  },
  {
    letter: "ਬ",
    name: "babbā",
    nameGurmukhi: "ਬੱਬਾ",
    sound: "b as in bus",
    ipa: "b",
    group: "labials",
    order: 28,
    example: { gurmukhi: "ਬੱਚਾ", roman: "baccā", english: "child" },
    strokeGuide: TOP_BAR,
  },
  {
    letter: "ਭ",
    name: "bhabbā",
    nameGurmukhi: "ਭੱਬਾ",
    sound: "bh — in practice a p sound with the voice dipping low",
    ipa: "pə̀",
    group: "labials",
    order: 29,
    example: { gurmukhi: "ਭੈਣ", roman: "bhaiṇ", english: "sister" },
    strokeGuide: TOP_BAR,
    note: "The last of the five tonal letters: ਘ ਝ ਢ ਧ ਭ.",
  },
  {
    letter: "ਮ",
    name: "mammā",
    nameGurmukhi: "ਮੰਮਾ",
    sound: "m as in map",
    ipa: "m",
    group: "labials",
    order: 30,
    example: { gurmukhi: "ਮਾਂ", roman: "mā̃", english: "mother" },
    strokeGuide: TOP_BAR,
  },

  /* ------------------------------ sonorants ----------------------------- */
  {
    letter: "ਯ",
    name: "yayyā",
    nameGurmukhi: "ਯੱਯਾ",
    sound: "y as in yes",
    ipa: "j",
    group: "sonorants",
    order: 31,
    example: { gurmukhi: "ਯਾਦ", roman: "yād", english: "memory" },
    strokeGuide: TOP_BAR,
  },
  {
    letter: "ਰ",
    name: "rārā",
    nameGurmukhi: "ਰਾਰਾ",
    sound: "r — a light tap of the tongue, as in Spanish pero",
    ipa: "ɾ",
    group: "sonorants",
    order: 32,
    example: { gurmukhi: "ਰੋਟੀ", roman: "roṭī", english: "roti, bread" },
    strokeGuide: "A single stroke: down and slightly curved, then the top bar.",
  },
  {
    letter: "ਲ",
    name: "lallā",
    nameGurmukhi: "ਲੱਲਾ",
    sound: "l as in let",
    ipa: "l",
    group: "sonorants",
    order: 33,
    example: { gurmukhi: "ਲੱਸੀ", roman: "lassī", english: "lassi" },
    strokeGuide: TOP_BAR,
  },
  {
    letter: "ਵ",
    name: "vāvā",
    nameGurmukhi: "ਵਾਵਾ",
    sound: "v or w — between the two English sounds",
    ipa: "ʋ",
    group: "sonorants",
    order: 34,
    example: { gurmukhi: "ਵੱਡਾ", roman: "vaḍḍā", english: "big" },
    strokeGuide: TOP_BAR,
  },
  {
    letter: "ੜ",
    name: "ṛāṛā",
    nameGurmukhi: "ੜਾੜਾ",
    sound: "ṛ — flick the curled-back tongue down off the roof of the mouth",
    ipa: "ɽ",
    group: "sonorants",
    order: 35,
    example: { gurmukhi: "ਘੋੜਾ", roman: "ghoṛā", english: "horse" },
    strokeGuide: TOP_BAR,
    neverInitial: true,
    note: "Never starts a word. It is a different sound from ਰ, not a variation of it — worth practising on its own.",
  },

  /* ------------------------- pairī̃ bindī letters ------------------------ */
  {
    letter: "ਸ਼",
    name: "sasse pairī̃ bindī",
    nameGurmukhi: "ਸ਼ੱਸ਼ਾ",
    sound: "sh as in ship",
    ipa: "ʃ",
    group: "extra",
    order: 36,
    example: { gurmukhi: "ਸ਼ਹਿਰ", roman: "śahir", english: "city" },
    strokeGuide: "Write ਸ, then add a single dot below it.",
    note: "ਸ with a dot underneath. The dot is called ਪੈਰੀਂ ਬਿੰਦੀ — a bindi at the foot.",
  },
  {
    letter: "ਖ਼",
    name: "khakkhe pairī̃ bindī",
    nameGurmukhi: "ਖ਼ੱਖ਼ਾ",
    sound: "kh made at the back of the throat, as in Scottish loch",
    ipa: "x",
    group: "extra",
    order: 37,
    example: { gurmukhi: "ਖ਼ਬਰ", roman: "xabar", english: "news" },
    strokeGuide: "Write ਖ, then add a single dot below it.",
    note: "Many speakers simply say ਖ instead. Both are widely understood.",
  },
  {
    letter: "ਗ਼",
    name: "gagge pairī̃ bindī",
    nameGurmukhi: "ਗ਼ੱਗ਼ਾ",
    sound: "a throaty g, like a French r made with the voice on",
    ipa: "ɣ",
    group: "extra",
    order: 38,
    example: { gurmukhi: "ਗ਼ਲਤ", roman: "ġalat", english: "wrong" },
    strokeGuide: "Write ਗ, then add a single dot below it.",
    note: "Often pronounced as plain ਗ in everyday speech.",
  },
  {
    letter: "ਜ਼",
    name: "jajje pairī̃ bindī",
    nameGurmukhi: "ਜ਼ੱਜ਼ਾ",
    sound: "z as in zoo",
    ipa: "z",
    group: "extra",
    order: 39,
    example: { gurmukhi: "ਸਬਜ਼ੀ", roman: "sabzī", english: "vegetable" },
    strokeGuide: "Write ਜ, then add a single dot below it.",
    note: "Very common. Without the dot the letter is j, so ਜ਼ and ਜ are genuinely different words.",
  },
  {
    letter: "ਫ਼",
    name: "phapphe pairī̃ bindī",
    nameGurmukhi: "ਫ਼ੱਫ਼ਾ",
    sound: "f as in fan",
    ipa: "f",
    group: "extra",
    order: 40,
    example: { gurmukhi: "ਫ਼ੋਨ", roman: "fon", english: "phone" },
    strokeGuide: "Write ਫ, then add a single dot below it.",
    note: "ਫ is ph with a puff of air; ਫ਼ is a true f.",
  },
  {
    letter: "ਲ਼",
    name: "lalle pairī̃ bindī",
    nameGurmukhi: "ਲ਼ੱਲ਼ਾ",
    sound: "l with the tongue curled back",
    ipa: "ɭ",
    group: "extra",
    order: 41,
    example: { gurmukhi: "ਵਾਲ਼", roman: "vāḷ", english: "hair" },
    strokeGuide: "Write ਲ, then add a single dot below it.",
    rare: true,
    note: "Added to the alphabet only recently and often written as plain ਲ. Recognise it; you will rarely need to write it.",
  },
];

export const letters: Letter[] = parseAll(letterSchema, raw, "letter");

export const lettersByChar = new Map(letters.map((letter) => [letter.letter, letter]));

/** The 35 ਪੈਂਤੀ, without the later pairī̃ bindī additions. */
export const painti = letters.filter((letter) => letter.group !== "extra");

export const extraLetters = letters.filter((letter) => letter.group === "extra");

export function getLetter(char: string): Letter | undefined {
  return lettersByChar.get(char);
}
