import { parseAll, vowelSchema, type Vowel } from "@/content/schema";

/**
 * The ten vowels (ਲਗਾਂ ਮਾਤਰਾਂ), each shown on the same consonant — ਕ — so the
 * learner sees the *sign* change and nothing else. This is the single most
 * important idea in reading Gurmukhi: a vowel sign is added to a consonant,
 * and where the mark sits has nothing to do with when it is pronounced.
 *
 * Sihari (ਿ) is the case that catches everyone: it is written to the LEFT of
 * the consonant but spoken AFTER it. ਕਿ is "ki", never "ik".
 */

const raw: unknown[] = [
  {
    sign: "",
    name: "muktā",
    nameGurmukhi: "ਮੁਕਤਾ",
    onKakka: "ਕ",
    onKakkaRoman: "ka",
    independent: "ਅ",
    independentRoman: "a",
    sound: "a short uh, as in the a of about",
    ipa: "ə",
    position: "none",
    order: 1,
    example: { gurmukhi: "ਘਰ", roman: "ghar", english: "house" },
    note: "No mark at all. A bare consonant already carries this short vowel — which is why ਘਰ is ghar, not gh-r.",
  },
  {
    sign: "ਾ",
    name: "kannā",
    nameGurmukhi: "ਕੰਨਾ",
    onKakka: "ਕਾ",
    onKakkaRoman: "kā",
    independent: "ਆ",
    independentRoman: "ā",
    sound: "a long aa, as in father",
    ipa: "aː",
    position: "after",
    order: 2,
    example: { gurmukhi: "ਮਾਤਾ", roman: "mātā", english: "mother" },
    note: "A single upright stroke after the letter.",
  },
  {
    sign: "ਿ",
    name: "sihārī",
    nameGurmukhi: "ਸਿਹਾਰੀ",
    onKakka: "ਕਿ",
    onKakkaRoman: "ki",
    independent: "ਇ",
    independentRoman: "i",
    sound: "a short i, as in sit",
    ipa: "ɪ",
    position: "before",
    order: 3,
    example: { gurmukhi: "ਕਿਤਾਬ", roman: "kitāb", english: "book" },
    note: "Written before the consonant but spoken after it. ਕਿ is ki, never ik. This trips up every beginner exactly once.",
  },
  {
    sign: "ੀ",
    name: "bihārī",
    nameGurmukhi: "ਬਿਹਾਰੀ",
    onKakka: "ਕੀ",
    onKakkaRoman: "kī",
    independent: "ਈ",
    independentRoman: "ī",
    sound: "a long ee, as in see",
    ipa: "iː",
    position: "after",
    order: 4,
    example: { gurmukhi: "ਰੋਟੀ", roman: "roṭī", english: "roti, bread" },
    note: "The long partner of sihari, and written on the other side.",
  },
  {
    sign: "ੁ",
    name: "auṅkaṛ",
    nameGurmukhi: "ਔਂਕੜ",
    onKakka: "ਕੁ",
    onKakkaRoman: "ku",
    independent: "ਉ",
    independentRoman: "u",
    sound: "a short u, as in put",
    ipa: "ʊ",
    position: "below",
    order: 5,
    example: { gurmukhi: "ਕੁੜੀ", roman: "kuṛī", english: "girl" },
    note: "A small hook below the letter.",
  },
  {
    sign: "ੂ",
    name: "dulaiṅkaṛ",
    nameGurmukhi: "ਦੁਲੈਂਕੜ",
    onKakka: "ਕੂ",
    onKakkaRoman: "kū",
    independent: "ਊ",
    independentRoman: "ū",
    sound: "a long oo, as in food",
    ipa: "uː",
    position: "below",
    order: 6,
    example: { gurmukhi: "ਦੂਰ", roman: "dūr", english: "far" },
    note: "Two hooks below: the long partner of aunkar.",
  },
  {
    sign: "ੇ",
    name: "lā̃",
    nameGurmukhi: "ਲਾਂ",
    onKakka: "ਕੇ",
    onKakkaRoman: "ke",
    independent: "ਏ",
    independentRoman: "e",
    sound: "a long ay, as in day",
    ipa: "eː",
    position: "above",
    order: 7,
    example: { gurmukhi: "ਸੇਬ", roman: "seb", english: "apple" },
    note: "A single stroke sloping above the top bar.",
  },
  {
    sign: "ੈ",
    name: "dulāvā̃",
    nameGurmukhi: "ਦੁਲਾਵਾਂ",
    onKakka: "ਕੈ",
    onKakkaRoman: "kai",
    independent: "ਐ",
    independentRoman: "ai",
    sound: "an open e, close to the a in cat",
    ipa: "ɛː",
    position: "above",
    order: 8,
    example: { gurmukhi: "ਪੈਸਾ", roman: "paisā", english: "money" },
    note: "Two strokes above, hence the name: dulavan is the doubled form of lan.",
  },
  {
    sign: "ੋ",
    name: "hoṛā",
    nameGurmukhi: "ਹੋੜਾ",
    onKakka: "ਕੋ",
    onKakkaRoman: "ko",
    independent: "ਓ",
    independentRoman: "o",
    sound: "a long o, as in go",
    ipa: "oː",
    position: "above",
    order: 9,
    example: { gurmukhi: "ਮੋਰ", roman: "mor", english: "peacock" },
  },
  {
    sign: "ੌ",
    name: "kanauṛā",
    nameGurmukhi: "ਕਨੌੜਾ",
    onKakka: "ਕੌ",
    onKakkaRoman: "kau",
    independent: "ਔ",
    independentRoman: "au",
    sound: "an open o, close to the aw in saw",
    ipa: "ɔː",
    position: "above",
    order: 10,
    example: { gurmukhi: "ਕੌਣ", roman: "kauṇ", english: "who" },
  },
];

export const vowels: Vowel[] = parseAll(vowelSchema, raw, "vowel");

export const vowelsBySign = new Map(vowels.map((vowel) => [vowel.sign, vowel]));

/**
 * The same ten vowels applied to a second consonant, so learners generalise
 * the rule instead of memorising the shapes of the ਕ series.
 */
export const secondSeries = {
  consonant: "ਮ",
  consonantRoman: "m",
  forms: [
    { gurmukhi: "ਮ", roman: "ma" },
    { gurmukhi: "ਮਾ", roman: "mā" },
    { gurmukhi: "ਮਿ", roman: "mi" },
    { gurmukhi: "ਮੀ", roman: "mī" },
    { gurmukhi: "ਮੁ", roman: "mu" },
    { gurmukhi: "ਮੂ", roman: "mū" },
    { gurmukhi: "ਮੇ", roman: "me" },
    { gurmukhi: "ਮੈ", roman: "mai" },
    { gurmukhi: "ਮੋ", roman: "mo" },
    { gurmukhi: "ਮੌ", roman: "mau" },
  ],
};
