import { parseAll, wordSchema, type Word } from "@/content/schema";

/**
 * The everyday things a first conversation needs: the house you are in, the
 * work you do, and the handful of adjectives that make a sentence say
 * something rather than just name a thing.
 *
 * These are here because the sentences in the course need them, not because a
 * list of nouns is worth memorising on its own. Each one appears in a lesson.
 */

const raw: unknown[] = [
  {
    gurmukhi: "ਘਰ",
    roman: "ghar",
    english: "house, home",
    category: "home",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਇਹ ਮੇਰਾ ਘਰ ਹੈ।",
    exampleRoman: "ih merā ghar hai.",
    exampleEnglish: "This is my house.",
    note: "ਘ is a g with breath behind it — closer to the gh of doghouse than to the g of go.",
  },
  {
    gurmukhi: "ਕਮਰਾ",
    roman: "kamrā",
    english: "room",
    category: "home",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਮੇਰਾ ਕਮਰਾ ਛੋਟਾ ਹੈ।",
    exampleRoman: "merā kamrā choṭā hai.",
    exampleEnglish: "My room is small.",
  },
  {
    gurmukhi: "ਦਰਵਾਜ਼ਾ",
    roman: "darvāzā",
    english: "door",
    category: "home",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਦਰਵਾਜ਼ਾ ਖੁੱਲ੍ਹਾ ਹੈ।",
    exampleRoman: "darvāzā khullhā hai.",
    exampleEnglish: "The door is open.",
  },
  {
    gurmukhi: "ਕੁਰਸੀ",
    roman: "kursī",
    english: "chair",
    category: "home",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "f",
    example: "ਕੁਰਸੀ ਉੱਤੇ ਬੈਠੋ।",
    exampleRoman: "kursī utte baiṭho.",
    exampleEnglish: "Sit on the chair.",
  },
  {
    gurmukhi: "ਮੇਜ਼",
    roman: "mez",
    english: "table",
    category: "home",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਕਿਤਾਬ ਮੇਜ਼ ਉੱਤੇ ਹੈ।",
    exampleRoman: "kitāb mez utte hai.",
    exampleEnglish: "The book is on the table.",
  },
  {
    gurmukhi: "ਕਿਤਾਬ",
    roman: "kitāb",
    english: "book",
    category: "school",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "f",
    example: "ਇਹ ਕਿਤਾਬ ਚੰਗੀ ਹੈ।",
    exampleRoman: "ih kitāb caṅgī hai.",
    exampleEnglish: "This book is good.",
    note: "Feminine, so the adjective ends in -ੀ: ਚੰਗੀ, not ਚੰਗਾ.",
  },
  {
    gurmukhi: "ਕੰਮ",
    roman: "kamm",
    english: "work, a job, a task",
    category: "work",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਮੇਰਾ ਕੰਮ ਖ਼ਤਮ ਹੋ ਗਿਆ।",
    exampleRoman: "merā kamm xatam ho giā.",
    exampleEnglish: "My work is finished.",
  },
  {
    gurmukhi: "ਪਿੰਡ",
    roman: "piṇḍ",
    english: "village",
    category: "places",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਸਾਡਾ ਪਿੰਡ ਸੋਹਣਾ ਹੈ।",
    exampleRoman: "sāḍā piṇḍ sohṇā hai.",
    exampleEnglish: "Our village is beautiful.",
    note: "Ask a Punjabi where they are from and the answer is usually a ਪਿੰਡ, even from someone who has never lived there.",
  },
  {
    gurmukhi: "ਸ਼ਹਿਰ",
    roman: "śahir",
    english: "city, town",
    category: "places",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਮੈਂ ਸ਼ਹਿਰ ਵਿੱਚ ਰਹਿੰਦਾ ਹਾਂ।",
    exampleRoman: "maĩ śahir vicc rahindā hā̃.",
    exampleEnglish: "I live in the city.",
  },
  {
    gurmukhi: "ਚੰਗਾ",
    roman: "caṅgā",
    english: "good",
    category: "adjectives",
    partOfSpeech: "adjective",
    difficulty: 1,
    example: "ਇਹ ਚੰਗਾ ਹੈ।",
    exampleRoman: "ih caṅgā hai.",
    exampleEnglish: "This is good.",
    note: "Changes with what it describes: ਚੰਗਾ ਘਰ, ਚੰਗੀ ਕਿਤਾਬ, ਚੰਗੇ ਬੱਚੇ. Also used on its own to mean all right, the way English says fine, then.",
  },
  {
    gurmukhi: "ਵੱਡਾ",
    roman: "vaḍḍā",
    english: "big; older",
    category: "adjectives",
    partOfSpeech: "adjective",
    difficulty: 1,
    example: "ਮੇਰਾ ਭਰਾ ਵੱਡਾ ਹੈ।",
    exampleRoman: "merā bharā vaḍḍā hai.",
    exampleEnglish: "My brother is older.",
    note: "Size and age are the same word: ਵੱਡਾ ਭਰਾ is an older brother, not a large one.",
  },
  {
    gurmukhi: "ਛੋਟਾ",
    roman: "choṭā",
    english: "small; younger",
    category: "adjectives",
    partOfSpeech: "adjective",
    difficulty: 1,
    example: "ਮੇਰਾ ਕਮਰਾ ਛੋਟਾ ਹੈ।",
    exampleRoman: "merā kamrā choṭā hai.",
    exampleEnglish: "My room is small.",
  },
  {
    gurmukhi: "ਬਹੁਤ",
    roman: "bahut",
    english: "very, a lot",
    category: "adjectives",
    partOfSpeech: "adverb",
    difficulty: 1,
    example: "ਦਾਲ ਬਹੁਤ ਸੁਆਦ ਹੈ।",
    exampleRoman: "dāl bahut suād hai.",
    exampleEnglish: "The dal is very tasty.",
  },
  {
    gurmukhi: "ਅੱਜ",
    roman: "ajj",
    english: "today",
    category: "time",
    partOfSpeech: "adverb",
    difficulty: 1,
    example: "ਅੱਜ ਸਬਜ਼ੀ ਬਣਾਈ ਹੈ।",
    exampleRoman: "ajj sabzī baṇāī hai.",
    exampleEnglish: "I have made vegetables today.",
  },
];

export const everyday: Word[] = parseAll(wordSchema, raw, "everyday word");
