import { parseAll, wordSchema, type Word } from "@/content/schema";

/**
 * Family, which in Punjabi is more precise than in English.
 *
 * There is no single word for grandmother: your father's mother is ਦਾਦੀ and
 * your mother's mother is ਨਾਨੀ, and the same split runs through grandfathers,
 * uncles and aunts. English speakers usually find this the first real sign
 * that they are learning a different way of describing the world, not just new
 * labels for the same one.
 */

const raw: unknown[] = [
  {
    gurmukhi: "ਪਰਿਵਾਰ",
    roman: "parivār",
    english: "family",
    category: "family",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਸਾਡਾ ਪਰਿਵਾਰ ਵੱਡਾ ਹੈ।",
    exampleRoman: "sāḍā parivār vaḍḍā hai.",
    exampleEnglish: "Our family is big.",
  },
  {
    gurmukhi: "ਮਾਂ",
    roman: "mā̃",
    english: "mother",
    category: "family",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "f",
    example: "ਮੇਰੀ ਮਾਂ ਘਰ ਹੈ।",
    exampleRoman: "merī mā̃ ghar hai.",
    exampleEnglish: "My mother is at home.",
    note: "The ਂ (bindi) puts the sound through the nose. Children usually say ਮੰਮੀ instead.",
  },
  {
    gurmukhi: "ਪਿਤਾ",
    roman: "pitā",
    english: "father",
    category: "family",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਮੇਰੇ ਪਿਤਾ ਜੀ ਕੰਮ ਤੇ ਹਨ।",
    exampleRoman: "mere pitā jī kamm te han.",
    exampleEnglish: "My father is at work.",
    note: "Usually said with ਜੀ after it. In everyday speech people more often say ਪਾਪਾ or ਡੈਡੀ; ਪਿਤਾ is the word you will see written.",
  },
  {
    gurmukhi: "ਭਰਾ",
    roman: "bharā",
    english: "brother",
    category: "family",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਮੇਰਾ ਭਰਾ ਵੱਡਾ ਹੈ।",
    exampleRoman: "merā bharā vaḍḍā hai.",
    exampleEnglish: "My brother is older.",
  },
  {
    gurmukhi: "ਭੈਣ",
    roman: "bhaiṇ",
    english: "sister",
    category: "family",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "f",
    example: "ਮੇਰੀ ਭੈਣ ਪੜ੍ਹਦੀ ਹੈ।",
    exampleRoman: "merī bhaiṇ paṛhdī hai.",
    exampleEnglish: "My sister studies.",
    note: "Ends in ਣ, the retroflex n — tongue curled back to the roof of the mouth, not the ਨ of English n.",
  },
  {
    gurmukhi: "ਪੁੱਤਰ",
    roman: "puttar",
    english: "son",
    category: "family",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਉਹ ਮੇਰਾ ਪੁੱਤਰ ਹੈ।",
    exampleRoman: "uh merā puttar hai.",
    exampleEnglish: "He is my son.",
    note: "Also used affectionately to any younger person, the way English uses son or lad.",
  },
  {
    gurmukhi: "ਧੀ",
    roman: "dhī",
    english: "daughter",
    category: "family",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "f",
    example: "ਉਹ ਮੇਰੀ ਧੀ ਹੈ।",
    exampleRoman: "uh merī dhī hai.",
    exampleEnglish: "She is my daughter.",
  },
  {
    gurmukhi: "ਬੱਚਾ",
    roman: "baccā",
    english: "child",
    category: "family",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਬੱਚਾ ਸੌਂ ਰਿਹਾ ਹੈ।",
    exampleRoman: "baccā saũ rihā hai.",
    exampleEnglish: "The child is sleeping.",
    note: "Plural ਬੱਚੇ. Words ending in -ਾ are nearly always masculine and nearly always change that -ਾ to -ੇ in the plural.",
  },
  {
    gurmukhi: "ਦਾਦਾ",
    roman: "dādā",
    english: "grandfather (father's father)",
    category: "family",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਮੇਰੇ ਦਾਦਾ ਜੀ ਪਿੰਡ ਰਹਿੰਦੇ ਹਨ।",
    exampleRoman: "mere dādā jī piṇḍ rahinde han.",
    exampleEnglish: "My grandfather lives in the village.",
  },
  {
    gurmukhi: "ਦਾਦੀ",
    roman: "dādī",
    english: "grandmother (father's mother)",
    category: "family",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "f",
    example: "ਮੇਰੀ ਦਾਦੀ ਜੀ ਕਹਾਣੀ ਸੁਣਾਉਂਦੇ ਹਨ।",
    exampleRoman: "merī dādī jī kahāṇī suṇāunde han.",
    exampleEnglish: "My grandmother tells a story.",
  },
  {
    gurmukhi: "ਨਾਨਾ",
    roman: "nānā",
    english: "grandfather (mother's father)",
    category: "family",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਮੇਰੇ ਨਾਨਾ ਜੀ ਆਏ ਹਨ।",
    exampleRoman: "mere nānā jī āe han.",
    exampleEnglish: "My grandfather has come.",
    note: "Your mother's side takes ਨਾਨਾ and ਨਾਨੀ; your father's side takes ਦਾਦਾ and ਦਾਦੀ. Punjabi never blurs the two.",
  },
  {
    gurmukhi: "ਨਾਨੀ",
    roman: "nānī",
    english: "grandmother (mother's mother)",
    category: "family",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "f",
    example: "ਮੈਂ ਆਪਣੀ ਨਾਨੀ ਨੂੰ ਮਿਲਿਆ।",
    exampleRoman: "maĩ āpṇī nānī nū̃ miliā.",
    exampleEnglish: "I met my grandmother.",
  },
];

export const family: Word[] = parseAll(wordSchema, raw, "family word");
