import { parseAll, wordSchema, type Word } from "@/content/schema";

/**
 * Food and drink — the vocabulary a learner uses first, because it is what
 * gets said at a table.
 *
 * Gender matters here more than anywhere else at this level, because the verb
 * and the adjective both have to agree with it: ਚਾਹ ਠੰਢੀ ਹੈ but ਦੁੱਧ ਠੰਢਾ ਹੈ.
 * Every noun below carries its gender for that reason.
 */

const raw: unknown[] = [
  {
    gurmukhi: "ਪਾਣੀ",
    roman: "pāṇī",
    english: "water",
    category: "food_drink",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਮੈਨੂੰ ਪਾਣੀ ਚਾਹੀਦਾ ਹੈ।",
    exampleRoman: "mainū̃ pāṇī cāhīdā hai.",
    exampleEnglish: "I need water.",
    note: "Three parts: ਪ + ਾ + ਣ + ੀ. The ਣ is retroflex — the tongue curls back, which is what makes it sound different from ਨ.",
  },
  {
    gurmukhi: "ਰੋਟੀ",
    roman: "roṭī",
    english: "bread; a meal",
    category: "food_drink",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "f",
    example: "ਰੋਟੀ ਤਿਆਰ ਹੈ।",
    exampleRoman: "roṭī tiār hai.",
    exampleEnglish: "The food is ready.",
    note: "It means flatbread, but ਰੋਟੀ ਖਾਧੀ? (have you eaten roti?) is how people ask whether you have eaten at all.",
  },
  {
    gurmukhi: "ਦੁੱਧ",
    roman: "duddh",
    english: "milk",
    category: "food_drink",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਬੱਚਾ ਦੁੱਧ ਪੀਂਦਾ ਹੈ।",
    exampleRoman: "baccā duddh pīndā hai.",
    exampleEnglish: "The child drinks milk.",
  },
  {
    gurmukhi: "ਚਾਹ",
    roman: "cāh",
    english: "tea",
    category: "food_drink",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "f",
    example: "ਚਾਹ ਪੀ ਲਓ।",
    exampleRoman: "cāh pī lao.",
    exampleEnglish: "Have some tea.",
    note: "Offered constantly, and refusing twice before accepting is normal.",
  },
  {
    gurmukhi: "ਦਾਲ",
    roman: "dāl",
    english: "lentils, dal",
    category: "food_drink",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "f",
    example: "ਦਾਲ ਬਹੁਤ ਸੁਆਦ ਹੈ।",
    exampleRoman: "dāl bahut suād hai.",
    exampleEnglish: "The dal is very tasty.",
  },
  {
    gurmukhi: "ਸਬਜ਼ੀ",
    roman: "sabzī",
    english: "vegetable; a cooked vegetable dish",
    category: "food_drink",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "f",
    example: "ਅੱਜ ਸਬਜ਼ੀ ਬਣਾਈ ਹੈ।",
    exampleRoman: "ajj sabzī baṇāī hai.",
    exampleEnglish: "I have made vegetables today.",
    note: "Spelled with ਜ਼ — ਜ with a dot underneath, which turns j into z. The dot only ever appears in words borrowed from Persian, Arabic or English.",
  },
  {
    gurmukhi: "ਚੌਲ",
    roman: "caul",
    english: "rice",
    category: "food_drink",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਮੈਨੂੰ ਚੌਲ ਪਸੰਦ ਹਨ।",
    exampleRoman: "mainū̃ caul pasand han.",
    exampleEnglish: "I like rice.",
    note: "Treated as plural in Punjabi — grains, not a mass — so the verb is ਹਨ, not ਹੈ.",
  },
  {
    gurmukhi: "ਫਲ",
    roman: "phal",
    english: "fruit",
    category: "food_drink",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਫਲ ਖਾਓ।",
    exampleRoman: "phal khāo.",
    exampleEnglish: "Eat fruit.",
    note: "ਫ is p with a puff of air after it, not the f of English fruit.",
  },
  {
    gurmukhi: "ਖੰਡ",
    roman: "khaṇḍ",
    english: "sugar",
    category: "food_drink",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "f",
    example: "ਚਾਹ ਵਿੱਚ ਖੰਡ ਪਾਓ।",
    exampleRoman: "cāh vicc khaṇḍ pāo.",
    exampleEnglish: "Put sugar in the tea.",
  },
  {
    gurmukhi: "ਲੂਣ",
    roman: "lūṇ",
    english: "salt",
    category: "food_drink",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਦਾਲ ਵਿੱਚ ਲੂਣ ਘੱਟ ਹੈ।",
    exampleRoman: "dāl vicc lūṇ ghaṭṭ hai.",
    exampleEnglish: "There is not enough salt in the dal.",
  },
  {
    gurmukhi: "ਦਹੀਂ",
    roman: "dahī̃",
    english: "yoghurt",
    category: "food_drink",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਮੈਂ ਦਹੀਂ ਖਾਂਦਾ ਹਾਂ।",
    exampleRoman: "maĩ dahī̃ khāndā hā̃.",
    exampleEnglish: "I eat yoghurt.",
  },
  {
    gurmukhi: "ਖਾਣਾ",
    roman: "khāṇā",
    english: "food, a meal",
    category: "food_drink",
    partOfSpeech: "noun",
    difficulty: 1,
    gender: "m",
    example: "ਖਾਣਾ ਤਿਆਰ ਹੈ।",
    exampleRoman: "khāṇā tiār hai.",
    exampleEnglish: "The food is ready.",
    note: "The same word is the verb to eat. Punjabi uses a verb's -ਣਾ form as a noun freely, exactly as English turns eating into a thing.",
  },
];

export const food: Word[] = parseAll(wordSchema, raw, "food word");
