import { parseAll, wordSchema, type Word } from "@/content/schema";

/**
 * Verbs, listed in the form a dictionary gives them: the -ਣਾ / -ਨਾ infinitive.
 *
 * Punjabi does not use that form the way English uses "to go" — it conjugates,
 * and the endings are the subject of their own lessons. But it is the form
 * every dictionary lists, the form that doubles as a noun (ਖਾਣਾ is both eating
 * and food), and the form that appears in the two patterns a beginner uses
 * constantly: ਮੈਨੂੰ … ਹੈ for what I have to do, and ਮੈਨੂੰ … ਆਉਂਦਾ ਹੈ for what I
 * know how to do. Most examples below use one of those, which is why they sound
 * alike — that repetition is the pattern, not a shortage of imagination.
 *
 * ਖਾਣਾ (to eat, and food) is taught in the food file.
 */

const raw: unknown[] = [
  {
    gurmukhi: "ਹੋਣਾ",
    roman: "hoṇā",
    english: "to be",
    category: "verbs",
    partOfSpeech: "verb",
    difficulty: 1,
    example: "ਮੈਨੂੰ ਤਿਆਰ ਹੋਣਾ ਹੈ।",
    exampleRoman: "mainū̃ tiār hoṇā hai.",
    exampleEnglish: "I have to get ready.",
    note: "The most important verb in the language, and the one you have already met: ਹਾਂ, ਹੈ, ਹੋ and ਹਨ are all ਹੋਣਾ, changed to match who is speaking.",
  },
  {
    gurmukhi: "ਜਾਣਾ",
    roman: "jāṇā",
    english: "to go",
    category: "verbs",
    partOfSpeech: "verb",
    difficulty: 1,
    example: "ਮੈਂ ਘਰ ਜਾਣਾ ਹੈ।",
    exampleRoman: "maĩ ghar jāṇā hai.",
    exampleEnglish: "I am going home.",
  },
  {
    gurmukhi: "ਆਉਣਾ",
    roman: "āuṇā",
    english: "to come",
    category: "verbs",
    partOfSpeech: "verb",
    difficulty: 1,
    example: "ਮੈਨੂੰ ਕੱਲ੍ਹ ਆਉਣਾ ਹੈ।",
    exampleRoman: "mainū̃ kallh āuṇā hai.",
    exampleEnglish: "I have to come tomorrow.",
    note: "ਕੱਲ੍ਹ means both yesterday and tomorrow. The verb tense tells you which one is meant, and nobody finds it confusing.",
  },
  {
    gurmukhi: "ਪੀਣਾ",
    roman: "pīṇā",
    english: "to drink",
    category: "verbs",
    partOfSpeech: "verb",
    difficulty: 1,
    example: "ਮੈਨੂੰ ਦੁੱਧ ਪੀਣਾ ਪਸੰਦ ਹੈ।",
    exampleRoman: "mainū̃ duddh pīṇā pasand hai.",
    exampleEnglish: "I like drinking milk.",
  },
  {
    gurmukhi: "ਕਰਨਾ",
    roman: "karnā",
    english: "to do, to make",
    category: "verbs",
    partOfSpeech: "verb",
    difficulty: 1,
    example: "ਮੈਨੂੰ ਕੰਮ ਕਰਨਾ ਹੈ।",
    exampleRoman: "mainū̃ kamm karnā hai.",
    exampleEnglish: "I have to work.",
    note: "Punjabi builds whole verbs out of a noun plus ਕਰਨਾ: ਕੰਮ ਕਰਨਾ to work, ਗੱਲ ਕਰਨਾ to talk, ਯਾਦ ਕਰਨਾ to remember.",
  },
  {
    gurmukhi: "ਬੋਲਣਾ",
    roman: "bolṇā",
    english: "to speak",
    category: "verbs",
    partOfSpeech: "verb",
    difficulty: 1,
    example: "ਮੈਨੂੰ ਪੰਜਾਬੀ ਬੋਲਣਾ ਆਉਂਦਾ ਹੈ।",
    exampleRoman: "mainū̃ pañjābī bolṇā āundā hai.",
    exampleEnglish: "I know how to speak Punjabi.",
    note: "ਆਉਂਦਾ ਹੈ literally says it comes to me. That is how Punjabi says someone can do something.",
  },
  {
    gurmukhi: "ਸਿੱਖਣਾ",
    roman: "sikkhṇā",
    english: "to learn",
    category: "verbs",
    partOfSpeech: "verb",
    difficulty: 1,
    example: "ਮੈਂ ਪੰਜਾਬੀ ਸਿੱਖਣਾ ਚਾਹੁੰਦਾ ਹਾਂ।",
    exampleRoman: "maĩ pañjābī sikkhṇā cāhundā hā̃.",
    exampleEnglish: "I want to learn Punjabi.",
    note: "Same root as ਸਿੱਖ — a Sikh is, literally, a learner.",
  },
  {
    gurmukhi: "ਪੜ੍ਹਨਾ",
    roman: "paṛhnā",
    english: "to read, to study",
    category: "verbs",
    partOfSpeech: "verb",
    difficulty: 1,
    example: "ਮੈਂ ਗੁਰਮੁਖੀ ਪੜ੍ਹਨਾ ਸਿੱਖ ਰਿਹਾ ਹਾਂ।",
    exampleRoman: "maĩ gurmukhī paṛhnā sikkh rihā hā̃.",
    exampleEnglish: "I am learning to read Gurmukhi.",
    note: "The ੍ਹ under the ੜ is a pairī̃ ਹ — an h tucked beneath the letter above it, because it would not fit alongside.",
  },
  {
    gurmukhi: "ਲਿਖਣਾ",
    roman: "likhṇā",
    english: "to write",
    category: "verbs",
    partOfSpeech: "verb",
    difficulty: 1,
    example: "ਮੈਨੂੰ ਗੁਰਮੁਖੀ ਲਿਖਣਾ ਆਉਂਦਾ ਹੈ।",
    exampleRoman: "mainū̃ gurmukhī likhṇā āundā hai.",
    exampleEnglish: "I know how to write Gurmukhi.",
  },
  {
    gurmukhi: "ਵੇਖਣਾ",
    roman: "vekhṇā",
    english: "to see, to look at",
    category: "verbs",
    partOfSpeech: "verb",
    difficulty: 1,
    example: "ਮੈਨੂੰ ਪੰਜਾਬ ਵੇਖਣਾ ਹੈ।",
    exampleRoman: "mainū̃ pañjāb vekhṇā hai.",
    exampleEnglish: "I want to see Punjab.",
    note: "ਦੇਖਣਾ is the same word with a d, and both are correct — which one you hear depends on where the speaker is from.",
  },
  {
    gurmukhi: "ਦੇਣਾ",
    roman: "deṇā",
    english: "to give",
    category: "verbs",
    partOfSpeech: "verb",
    difficulty: 1,
    example: "ਮੈਨੂੰ ਜਵਾਬ ਦੇਣਾ ਹੈ।",
    exampleRoman: "mainū̃ javāb deṇā hai.",
    exampleEnglish: "I have to give an answer.",
  },
  {
    gurmukhi: "ਲੈਣਾ",
    roman: "laiṇā",
    english: "to take, to get",
    category: "verbs",
    partOfSpeech: "verb",
    difficulty: 1,
    example: "ਮੈਨੂੰ ਦੁੱਧ ਲੈਣਾ ਹੈ।",
    exampleRoman: "mainū̃ duddh laiṇā hai.",
    exampleEnglish: "I have to get milk.",
  },
  {
    gurmukhi: "ਰਹਿਣਾ",
    roman: "rahiṇā",
    english: "to live, to stay",
    category: "verbs",
    partOfSpeech: "verb",
    difficulty: 1,
    example: "ਮੈਨੂੰ ਇੱਥੇ ਰਹਿਣਾ ਹੈ।",
    exampleRoman: "mainū̃ itthe rahiṇā hai.",
    exampleEnglish: "I have to stay here.",
    note: "Where do you live? is ਤੁਸੀਂ ਕਿੱਥੇ ਰਹਿੰਦੇ ਹੋ? — the same verb, conjugated.",
  },
];

export const verbs: Word[] = parseAll(wordSchema, raw, "verbs word");
